import { env } from './env';
export type EventName='sign_up_started'|'sign_up_completed'|'login_completed'|'logout_completed'|'onboarding_started'|'onboarding_step_viewed'|'birth_time_status_selected'|'onboarding_completed'|'person_creation_started'|'person_created'|'person_updated'|'person_deleted'|'person_archived'|'match_creation_started'|'match_focus_selected'|'match_generation_requested'|'match_generation_completed'|'match_generation_failed'|'match_report_viewed'|'match_report_saved'|'share_card_generated'|'share_started'|'ask_screen_viewed'|'suggested_question_clicked'|'astrology_question_submitted'|'astrology_answer_completed'|'astrology_answer_failed'|'astrology_answer_feedback'|'primary_cta_clicked'|'pricing_interest_clicked'|'legal_page_viewed'|'page_view'|'blueprint_screen_viewed'|'blueprint_generation_requested'|'blueprint_generation_completed'|'blueprint_generation_failed'|'blueprint_section_expanded'|'blueprint_regeneration_requested'|'relationship_creation_started'|'relationship_created'|'relationship_opened'|'relationship_archived'|'compatibility_calculation_requested'|'compatibility_calculation_completed'|'compatibility_calculation_failed'|'compatibility_report_generation_requested'|'compatibility_report_generated'|'compatibility_report_viewed'|'compatibility_category_expanded'|'compatibility_report_regeneration_requested'|'add_person_cta_clicked'|'analyse_relationship_cta_clicked'|'ask_about_relationship_cta_clicked'|'share_report_cta_clicked';
type Params=Record<string,string|number|boolean|undefined>; declare global{interface Window{gtag?:(command:string,name:string,params?:Params)=>void}}
const consent=()=>localStorage.getItem('am:analytics-consent')==='granted';
const forbiddenKey=/(^|_)(name|alias|email|uid|uuid|id|birth|place|location|latitude|longitude|note|content|question|answer|factor|report)(_|$)/i;
const uuid=/\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/gi;
export function sanitizeAnalyticsParams(params:Params){
  return Object.fromEntries(Object.entries(params)
    .filter(([key,value])=>!forbiddenKey.test(key)&&['string','number','boolean'].includes(typeof value))
    .map(([key,value])=>[key,typeof value==='string'?value.replace(uuid,':private'):value])) as Params;
}
export function track(name:EventName,params:Params={}){if(env.VITE_ENABLE_ANALYTICS!=='true'||!consent())return;window.gtag?.('event',name,sanitizeAnalyticsParams(params))}
export function setAnalyticsConsent(value:boolean){localStorage.setItem('am:analytics-consent',value?'granted':'denied');window.gtag?.('consent','update',{'analytics_storage':value?'granted':'denied'} as Params)}
